version: "2"

services:
  mariadb:
    image: mariadb:latest 
    restart: always
    networks:
      - network1 
    volumes:
      - ./data:/var/lib/mysql
      - ./database.ini:/var/www/html/config/database.ini
    environment:
      MYSQL_ROOT_PASSWORD: omeka 
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network1 
    ports:
      - "8080:80"
    links:
      - mariadb:db

  omeka:
    depends_on:
      - mariadb
    image: dodeeric/omeka-s:latest 
    restart: always
    networks:
      - network1 
    ports:
      - "80:80"
    links:
      - mariadb:db
    volumes:
      - ./omeka:/var/www/html/volume
      - ./media:/var/www/html/files

volumes:
  mariadb:
  omeka:

networks:
  network1:  
